### ISSUE TITLE
Add specific units ("UnitsAppearsInCombat") that may appear in combat

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#11]
* [ ] Add specific units for Necrotic Wake #35
* [ ] Add specific units for Plaguefall #36
* [ ] Add specific units for De Other Side #37
* [ ] Add specific units for Halls of Atonement #38
* [ ] Add specific units for Spires of Ascension #39
* [ ] Add specific units for Theater of Pain #40
* [ ] Add specific units for Mists of Tirna Scithe #41
* [ ] Add specific units for Sanguine Depths #42
