### ISSUE TITLE
Add avoidable spells and debuffs for SL dungeons

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#3]
* [x] Add avoidable spells and debuffs for Necrotic Wake #27
* [x] Add avoidable spells and debuffs for Plaguefall #28
* [x] Add avoidable spells and debuffs for De Other Side #29
* [x] Add avoidable spells and debuffs for Halls of Atonement #30
* [x] Add avoidable spells and debuffs for Spires of Ascension #31
* [x] Add avoidable spells and debuffs for Theater of Pain #32
* [x] Add avoidable spells and debuffs for Mists of Tirna Scithe #33
* [x] Add avoidable spells and debuffs for Sanguine Depths #34
