### ISSUE TITLE
Add spells to interrupt for SL challenges

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#4]
* [x] Add spells to interrupt for Necrotic Wake #43
* [x] Add spells to interrupt for Plaguefall #44
* [x] Add spells to interrupt for De Other Side #45
* [x] Add spells to interrupt for Halls of Atonement #46
* [x] Add spells to interrupt for Spires of Ascension #47
* [x] Add spells to interrupt for Theater of Pain #48
* [x] Add spells to interrupt for Mists of Tirna Scithe #49
* [x] Add spells to interrupt for Sanguine Depths #50
