### ISSUE TITLE
Add Units ("SLDamageDoneToSpecificUnits") to track taken damage

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#5]
* [x] Add units to track taken damage for Necrotic Wake #93
* [x] Add units to track taken damage for Plaguefall #94
* [x] Add units to track taken damage for De Other Side #95
* [x] Add units to track taken damage for Halls of Atonement #96
* [x] Add units to track taken damage for Spires of Ascension #97
* [x] Add units to track taken damage for Theater of Pain #98
* [x] Add units to track taken damage for Mists of Tirna Scithe #99
* [x] Add units to track taken damage for Sanguine Depths #100
