### ISSUE TITLE
Add Usable Items ("SLSpecificItemsUsedByPartyMembers") for SL

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#6]
* [ ] Add Usable Dungeon Trinkets #51
* [x] Add Usable Raid Trinkets #52
* [x] Add Usable Proffesions Items #53
* [x] Add Usable PvP Trinkets #54
