### ISSUE TITLE
Add casts ("SpecificCastsDoneByPartyMembers") done by party members

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/my-dungeons-book#8]
* [x] Add special casts in the Necrotic Wake #55
* [ ] Add special casts in the Plaguefall #56
* [x] Add special casts in the De Other Side #57
* [x] Add special casts in the Halls of Atonement #58
* [ ] Add special casts in the Spires of Ascension #59
* [ ] Add special casts in the Theater of Pain #60
* [x] Add special casts in the Mists of Tirna Scithe #61
* [x] Add special casts in the Sanguine Depths #62
